PortfolioDatabase/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
# Imports to server user uploaded files during development
from django.conf import settings
from django.conf.urls.static import static
# Custom views
from portfolio.models import Hobby, Portfolio
from portfolio.views import portfolio_view, portfolio_detail_view, portfolio_manage_view, portfolio_upsert_view, portfolio_delete_view
from portfolio.views import contact_view, hobbies_view, home_view, hobbies_detail_view

urlpatterns = [
    path('', home_view, name='home'), # Change the index page
    path('contact/', contact_view, name='contact'), # Send an message


    path('hobbies/', hobbies_view, name='hobbies'),
    # hobbies/:id
    path('hobbies/<int:hobby_id>/', hobbies_detail_view, name='hobbies_detail'),


    path('portfolio/', portfolio_view, name='portfolio'),
    path('portfolio/<int:portfolio_id>/', portfolio_detail_view, name='portfolio_detail'),
    path('portfolio/manage/', portfolio_manage_view, name='portfolio_manage'),                      # An overview of the portfolio items
    path('portfolio/manage/<int:portfolio_id>', portfolio_upsert_view, name='portfolio_upsert'),    # Mange create and delete for portfolio
    path('portfolio/delete/<int:portfolio_id>', portfolio_delete_view, name='portfolio_delete'),    # Delete items from the portfolio


    path("users/", include("users.urls")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.views import register_view, profile_view
from django.contrib.auth import views as authentication_views

from .forms import UserLoginForm

app_name = "users"
urlpatterns = [
    # Get login and logout view from django
    # Default looks up for templates in registration/ so we need to change it with template name
    # Login also requires an accounts/profile/ template
    path('login/', authentication_views.LoginView.as_view(template_name="users/login.html", extra_context={'site_title': "Login"}, authentication_form=UserLoginForm), name='login'),
    path('logout/', authentication_views.LogoutView.as_view(template_name="users/logout.html", extra_context={'site_title': "Logout"}), name='logout'),


    # Create a custom register view
    path('register/', register_view, name='register'),
    path('profile/', profile_view, name='profile'),

]

templates/base.html
<!DOCTYPE html>
<html lang="en" class="h-100">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Portfolio -
    {{ site_title }}
  </title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  {% load static %}
  <link rel="stylesheet" href="{% static 'styles/style.css' %}">
  <link rel="icon" type="image/x-icon" href="{% static 'images/NewChicken.ico' %}">
  {% block header %}
  {% endblock %}
</head>

<body class="bd-main h-100">
  <header class="bd-header">
    {% include 'navbar.html' %}
  </header>
  <main class="h-100">
    <!-- Display messages -->
    {% if messages %}
    {% for message in messages %}
    <div class="float-end alert alert-{{ message.tags }} alert-dismissible fade show me-md-4" role="alert">
      {{ message }}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
    {% endif %}
    <div class="container-fluid container-xxl pt-3 py-pd-4 bd-content h-100">
      {% block content %}
      {% endblock %}
    </div>
  </main>
  <footer>
  </footer>
</body>

</html>

templates/contact.html
{% extends 'base.html' %}

{% block content %}
<h1>Contact</h1>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-6">
      <h2 class="text-center">korbindansie@mail.weber.edu</h2>
      <p>
        Hello, my name is korbin dansie and I look forward to working with you.
      </p>
    </div>
    <div class="col-md-6">
      <div class="card" style="border-radius: 1rem;">
        <div class="card-body p-5 text-center">
          <div class="">
            <h2 class="fw-bold mb-2 text-uppercase">Get in touch</h2>
            <form method="POST">
              {% csrf_token %}
              <div class="form-outline form-white mb-4">
                {{ form.name }}
                {{ form.name.errors }}
              </div>

              <div class="form-outline form-white mb-4">
                {{ form.email }}
                {{ form.email.errors }}
              </div>
              <div class="form-outline form-white mb-4">
                {{ form.message }}
                {{ form.message.errors }}
              </div>
              <button class="btn btn-outline-primary btn-lg px-5" type="submit">Submit</button>
            </form>
            {% if form.errors %}
            <p class="alert alert-danger my-2 py-1" role="alert">Error: Some information is incorrect or missing</p>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/hobbies.html
{% extends 'base.html' %}

{% block content %}
<h1 class="h1">Hobbies</h1>
<table class="table table-striped">
    <tr>
        <th>Name</th>
        <th>Description</th>
    </tr>
    {% for item in hobby_list %}
    <tr>
        <td class="fw-bold" scope="row">
            {{item.name}}
        </td>
        <td>
            {{item.description}}
        </td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<h2>Hi, I'm Korbin Dansie</h2>
<div class="row">
    <div class="col-md-8">
        <h1>I am an computer engineer, alway eager to learn more.</h1>
        <p>I found my love of programming back in high school. When I so innocently decided to take just one programming course. After that, I was hooked. I then began pursuing a bachelor's degree in software engineering.</p>        
    </div>
    <div class="col-md-4">
        <img src="{% static 'images/Korbin_2022_Close.JPG' %}" alt="A picture of myself" class="rounded img-fluid w-100">    
    </div>
</div>
{% endblock %}

templates/navbar.html
<nav class="container-xxl bd-gutter navbar navbar-expand-sm navbar-dark bd-header">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand bd-navbar-brand" href="{% url 'home' %}">Home</a>
    </div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapsable" aria-controls="navbarCollapsable" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapsable">
      <ul class="navbar-nav navbar-left me-auto mb-2 mb-sm-0">
        <li class="nav-item">
          <a class="nav-link bd-nav-item" href="{% url 'hobbies' %}">Hobbies</a>
        </li>
        <li class="nav-item">
          <a class="nav-link bd-nav-item" href="{% url 'portfolio' %}">Portfolio</a>
        </li>
        <li class="nav-item">
          <a class="nav-link bd-nav-item" href="{% url 'contact' %}">Contact</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <div class="btn-group">
            <button type="button" class="nav-link dropdown-toggle bd-nav-item"  data-bs-toggle="dropdown" data-bs-target="#dropdown-admin" aria-expanded="false">Admin</button>
            <ul class="dropdown-menu" role="menu" id="dropdown-admin">
              <li><a class="dropdown-item" href="{% url 'portfolio_manage' %}">Manage Portfolio</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'admin:index' %}">Django Dashboard</a></li>
            </ul>  
          </div>
        </li>
        {% endif %}
      </ul>
      <ul class="navbar-nav navbar-right ms-auto mb-2 mb-sm-0">
        {% if not user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link bd-login-btn" href="{% url 'users:login' %}">Login / Register</a>
        </li>
        {% else %}
        <li class="nav-item">
          <div class="btn-group">
            <button type="button" class="btn btn-secondary dropdown-toggle bd-login-btn" data-bs-toggle="dropdown" data-bs-target="#dropdown-profile" aria-expanded="false">
              Hello,
              {{ user.username }}
            </button>
            <ul class="dropdown-menu" id="dropdown-profile">
              <!-- <li><a class="dropdown-item" href="{% url 'users:profile' %}">Profile</a></li>
              <li><hr class="dropdown-divider"></li> -->
              <li><a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a></li>
            </ul>  
          </div>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>